Models/Salario.cs
using System.ComponentModel.DataAnnotations;

namespace GerenciadorDespesas.Models
{
    public class Salario
    {
        public int SalarioId { get; set; }
        public int MesId { get; set; }
        public Mes Meses { get; set; }

        [Required(ErrorMessage ="Campo Obrigatório.")]
        [Range(0, double.MaxValue,ErrorMessage ="Valor Inválido.")]
        public double Valor { get; set; }
    }
}

Controllers/SalariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GerenciadorDespesas.Models;

namespace GerenciadorDespesas.Controllers
{
    public class SalariosController : Controller
    {
        private readonly AppDbContext _context;

        public SalariosController(AppDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Salarios.Include(s => s.Meses);
            return View(await appDbContext.ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> Index(string txtPesquisar)
        {
            if (!String.IsNullOrEmpty(txtPesquisar))
            {
                return View(await _context.Salarios.Include(s => s.Meses).Where(m => m.Meses.Nome.ToUpper().Contains(txtPesquisar.ToUpper())).ToListAsync());
            }

            return View(await _context.Salarios.Include(s => s.Meses).ToListAsync());
        }

        // GET: Salarios/Create
        public IActionResult Create()
        {
            ViewData["MesId"] = new SelectList(_context.Meses.Where(s => s.MesId != s.Salarios.MesId), "MesId", "Nome");
            return View();
        }

        // POST: Salarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SalarioId,MesId,Valor")] Salario salario)
        {
            if (ModelState.IsValid)
            {
                TempData["Confirmacao"] = "O salário foi cadastrado com sucesso!";
                _context.Add(salario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MesId"] = new SelectList(_context.Meses.Where(s => s.MesId != s.Salarios.MesId), "MesId", "Nome", salario.MesId);
            return View(salario);
        }

        // GET: Salarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Salarios == null)
            {
                return NotFound();
            }

            var salario = await _context.Salarios.FindAsync(id);
            if (salario == null)
            {
                return NotFound();
            }
            ViewData["MesId"] = new SelectList(_context.Meses.Where(s => s.MesId == s.Salarios.MesId), "MesId", "Nome", salario.MesId);
            return View(salario);
        }

        // POST: Salarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SalarioId,MesId,Valor")] Salario salario)
        {
            if (id != salario.SalarioId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    TempData["Confirmacao"] = "O salário foi atualizado com sucesso!";
                    _context.Update(salario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SalarioExists(salario.SalarioId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MesId"] = new SelectList(_context.Meses.Where(s => s.MesId == s.Salarios.MesId), "MesId", "Nome", salario.MesId);
            return View(salario);
        }
                
        // POST: Salarios/Delete/5
        [HttpPost]        
        public async Task<IActionResult> Delete(int id)
        {            
            var salario = await _context.Salarios.FindAsync(id);
            TempData["Confirmacao"] = "O salário foi excluído com sucesso!";
            if (salario != null)
            {                
                _context.Salarios.Remove(salario);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SalarioExists(int id)
        {
          return _context.Salarios.Any(e => e.SalarioId == id);
        }
    }
}

Views/Salarios/Create.cshtml
@model GerenciadorDespesas.Models.Salario

@{
    ViewData["Title"] = "Novo Salário";
}

<div class="formulario">
<h6>Salários</h6>
<hr />
<div class="row">
    <div class="col-md-4">
            <form asp-action="Create" class="form border rounded">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MesId" class="control-label">Mês</label>
                <select asp-for="MesId" class ="form-control" asp-items="ViewBag.MesId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-outline-success btn-sm" /> &nbsp;
                <a asp-action="Index" class="btn btn-outline-dark btn-sm">Voltar</a>
            </div>
        </form>
    </div>
</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Salarios/Edit.cshtml
@model GerenciadorDespesas.Models.Salario

@{
    ViewData["Title"] = "Atualizar Salário";
}

<div class="formulario">
<h6>Atualizar Salário</h6>
<hr />
<div class="row">
    <div class="col-md-4">
            <form asp-action="Edit" class="form border rounded">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SalarioId" />
            <div class="form-group">
                <label asp-for="MesId" class="control-label">Mês</label>
                <select asp-for="MesId" class="form-control" asp-items="ViewBag.MesId"></select>
                <span asp-validation-for="MesId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                    <input type="submit" value="Salvar" class="btn btn-outline-success btn-sm" /> &nbsp;
                <a asp-action="Index" class="btn btn-outline-dark btn-sm">Voltar</a>
            </div>
        </form>
    </div>
</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Salarios/Index.cshtml
@model IEnumerable<GerenciadorDespesas.Models.Salario>

@{
    ViewData["Title"] = "Salários Cadastrados";
}

<div class="tabela">
    <div class="container">
        <h6>Salários Cadastrados</h6>
        <p class="btnNovo">
            <a asp-action="Create" class="btn btn-outline-primary btn-sm ">Novo Salário</a>
        </p>

        @if (TempData["Confirmacao"] != null)
        {
            <h6 class="alert alert-success">
                @TempData["Confirmacao"]
            </h6>
        }

        <form asp-action="Index" asp-controller="Salarios" method="post">
            <div class="form-group">
                <div class="input-group col-md-6">
                    <input class="form-control" name="txtPesquisar" />
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-outline-dark"><i class="fas fa-search-plus"></i></button>
                    </div>
                </div>
            </div>
        </form>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Meses)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Valor)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
        @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Meses.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Valor)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.SalarioId" class="btn btn-outline-info btn-sm">Atualizar</a> |                
                        <a onclick="ExibirModal(@item.SalarioId)" class="btn btn-outline-danger btn-sm">Excluir</a>
                    </td>
                </tr>
        }
            </tbody>
        </table>
    </div>
</div>

<!--Tela Modal-->
<div class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Excluir</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Deseja prosseguir com a exclusão do salário?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary btnExcluir">Sim</button>
                <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">Não</button>
            </div>
        </div>
    </div>
</div>

<!--Função Ajax para exibir modal-->
@section Scripts{
    <script>
        function ExibirModal(id) {
            
            $(".modal").modal();

            $(".btnExcluir").on('click', function () {
                $.ajax({
                    url: "Salarios/Delete",
                    method: "POST",
                    data: { id: id },
                    success: function (data) {
                        $(".modal").modal('hide');
                        location.reload(true);
                    }
                });
            });
        }
    </script>
}