Models/Despesa.cs
using System.ComponentModel.DataAnnotations;

namespace GerenciadorDespesas.Models
{
    public class Despesa
    {
        public int DespesaId { get; set; }
        public int MesId { get; set; }
        public Mes Meses { get; set; }
        public int TipoDespesaId { get; set; }
        public TipoDespesa TipoDespesa { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório.")]
        [Range(0, double.MaxValue, ErrorMessage = "Valor Inválido.")]
        public double Valor { get; set; }
    }
}

Controllers/DespesasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GerenciadorDespesas.Models;
using X.PagedList;
using GerenciadorDespesas.ViewModels;

namespace GerenciadorDespesas.Controllers
{
    public class DespesasController : Controller
    {
        private readonly AppDbContext _context;

        public DespesasController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Despesas
        public async Task<IActionResult> Index(int? pagina)
        {
            const int itensPagina = 10;
            int numeroPagina = (pagina ?? 1);

            ViewData["Meses"] = new SelectList(_context.Meses.Where(x => x.MesId == x.Salarios.MesId), "MesId", "Nome");

            var appDbContext = _context.Despesas.Include(d => d.Meses).Include(d => d.TipoDespesa).OrderBy(d => d.MesId);
            return View(await appDbContext.ToPagedListAsync(numeroPagina, itensPagina));
        }              

        // GET: Despesas/Create
        public IActionResult Create()
        {
            ViewData["MesId"] = new SelectList(_context.Meses, "MesId", "Nome");
            ViewData["TipoDespesaId"] = new SelectList(_context.TipoDespesas, "TipoDespesaId", "Nome");
            return View();
        }

        // POST: Despesas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DespesaId,MesId,TipoDespesaId,Valor")] Despesa despesa)
        {
            if (ModelState.IsValid)
            {
                TempData["Confirmacao"] = "Despesa cadastrada com sucesso!";
                _context.Add(despesa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MesId"] = new SelectList(_context.Meses, "MesId", "Nome", despesa.MesId);
            ViewData["TipoDespesaId"] = new SelectList(_context.TipoDespesas, "TipoDespesaId", "Nome", despesa.TipoDespesaId);
            return View(despesa);
        }

        // GET: Despesas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Despesas == null)
            {
                return NotFound();
            }

            var despesa = await _context.Despesas.FindAsync(id);
            if (despesa == null)
            {
                return NotFound();
            }
            ViewData["MesId"] = new SelectList(_context.Meses, "MesId", "Nome", despesa.MesId);
            ViewData["TipoDespesaId"] = new SelectList(_context.TipoDespesas, "TipoDespesaId", "Nome", despesa.TipoDespesaId);
            return View(despesa);
        }

        // POST: Despesas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DespesaId,MesId,TipoDespesaId,Valor")] Despesa despesa)
        {
            if (id != despesa.DespesaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    TempData["Confirmacao"] = "Despesa atualizada com sucesso!";
                    _context.Update(despesa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DespesaExists(despesa.DespesaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MesId"] = new SelectList(_context.Meses, "MesId", "Nome", despesa.MesId);
            ViewData["TipoDespesaId"] = new SelectList(_context.TipoDespesas, "TipoDespesaId", "Nome", despesa.TipoDespesaId);
            return View(despesa);
        }
        
        // POST: Despesas/Delete/5
        [HttpPost]       
        public async Task<IActionResult> Delete(int id)
        {            
            var despesa = await _context.Despesas.FindAsync(id);
            TempData["Confirmacao"] = "A despesa foi excluída com sucesso!";
            if (despesa != null)
            {
                _context.Despesas.Remove(despesa);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DespesaExists(int id)
        {
          return _context.Despesas.Any(e => e.DespesaId == id);
        }

        public JsonResult GastosTotaisMes(int mesId)
        {
            GastosTotaisMesViewModel gastos = new GastosTotaisMesViewModel();
            gastos.ValorTotalGasto = _context.Despesas.Where(d => d.Meses.MesId == mesId).Sum(d => d.Valor);
            gastos.Salario = _context.Salarios.Where(s => s.Meses.MesId == mesId).Select(s => s.Valor).FirstOrDefault();

            return Json(gastos);
        }

        public JsonResult GastoMes(int mesId)
        {
            var query = from despesas in _context.Despesas
                        where despesas.Meses.MesId == mesId 
                        group despesas by despesas.TipoDespesa.Nome into g
                        select new
                        {
                            TiposDespesas = g.Key,
                            Valores = g.Sum(d => d.Valor)
                        };

            return Json(query);
            
        }

        public JsonResult GastosTotais()
        {
            var query = _context.Despesas
                .OrderBy(m => m.Meses.MesId)
                .GroupBy(m => m.Meses.MesId)
                .Select(d => new {NomeMeses = d.Select(x => x.Meses.Nome)
                .Distinct(),Valores = d.Sum(x => x.Valor) });

            return Json(query);
        }

    }
}

ViewComponents/EstatisticasViewComponent.cs
using GerenciadorDespesas.Models;
using GerenciadorDespesas.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace GerenciadorDespesas.ViewComponents
{
    public class EstatisticasViewComponent : ViewComponent
    {
        private readonly AppDbContext _context;

        public EstatisticasViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            EstatisticasViewModel estatisticas = new EstatisticasViewModel();

            estatisticas.MenorDespesa = _context.Despesas.Min(x => x.Valor);

            estatisticas.MaiorDespesa = _context.Despesas.Max(x => x.Valor);

            estatisticas.QuantidadeDespesas = _context.Despesas.Count();

            return View(estatisticas);
        }
    }
}

Views/Despesas/Create.cshtml
@model GerenciadorDespesas.Models.Despesa

@{
    ViewData["Title"] = "Nova Despesa";
}

<div class="formulario">
<h6>Nova Despesa</h6>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" class="form border rounded">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MesId" class="control-label">Mês</label>
                <select asp-for="MesId" class ="form-control" asp-items="ViewBag.MesId"></select>
            </div>
            <div class="form-group">
                <label asp-for="TipoDespesaId" class="control-label">Tipo de Despesa</label>
                <div class="input-group">
                        <select asp-for="TipoDespesaId" class="form-control" asp-items="ViewBag.TipoDespesaId"></select>
                        <div class="input-group-append">
                            <button type="button" class="btn btn-outline-info" data-toggle="tooltip" data-placement="right" title="Adicionar Novo Tipo de Despesa" onclick="MostrarModal()">
                                <i class="fas fa-plus-square"></i>
                            </button>
                        </div>
                </div>
                
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-outline-success btn-sm" /> &nbsp;
                <a asp-action="Index" class="btn btn-outline-dark btn-sm">Voltar</a>
            </div>
        </form>
    </div>
</div>
</div>

<!--Tela Modal Adicionar Nova Despesa-->
<div class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Adicionar Nova Despesa</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <input class="form-control txtDespesa"/>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary btnAdicionar">Adicionar</button>
                <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(function (){
            $('[data-toggle = "tooltip"]').tooltip();
        });

        function MostrarModal(){
            $(".modal").modal();
            $(".btnAdicionar").on('click', function (){
                var txtDespesa = $(".txtDespesa").val();

                $.ajax({
                    url:"/TipoDespesas/AdicionarTipoDespesa",
                    method:"POST",
                    data:{txtDespesa: txtDespesa},
                    success:function(data){
                        if(!data){
                            $(".modal").modal('hide');
                            $(".modal").modal('dispose');
                            $(".btnAdicionar").unbind('click');
                            $(".txtDespesa").val('');
                            alert("Tipo de despesa já cadastrada!");
                        }
                        else location.reload(true);
                    }
                })
            });
        }
    </script>
}

Views/Despesas/Edit.cshtml
@model GerenciadorDespesas.Models.Despesa

@{
    ViewData["Title"] = "Atualizar Despesa";
}

<div class="formulario">
<h6>Atualizar Despesa</h6>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" class="form border rounded" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="DespesaId" />
            <div class="form-group">
                <label asp-for="MesId" class="control-label"></label>
                <select asp-for="MesId" class="form-control" asp-items="ViewBag.MesId"></select>
                <span asp-validation-for="MesId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoDespesaId" class="control-label"></label>
                <select asp-for="TipoDespesaId" class="form-control" asp-items="ViewBag.TipoDespesaId"></select>
                <span asp-validation-for="TipoDespesaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-outline-success btn-sm" /> &nbsp;
                <a asp-action="Index" class="btn-outline-dark btn-sm">Voltar</a>
            </div>
        </form>
    </div>
</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Despesas/Index.cshtml
@model X.PagedList.IPagedList<GerenciadorDespesas.Models.Despesa>
@using X.PagedList.Mvc.Core
@using X.PagedList.Web.Common

@{
    ViewData["Title"] = "Despesas Cadastradas";
}

<div class="tabela">
    <div class="container">
        <p class="btnNovo">
            <a asp-action="Create" class="btn btn-outline-primary btn-sm">Nova Despesa</a>
        </p>

        @if (TempData["Confirmacao"] != null)
        {
            <h6 class="alert alert-success">@TempData["Confirmacao"]</h6>
        }

        <div class="row justify-content-md-center">
            <div class="form-group row">
                <label class="col-sm-3 col-form-label"><strong>Mês</strong></label>
                <div class="col-sm-9">
                    <select class="form-control escolhaMes" asp-items="ViewBag.Meses"></select>
                </div>
            </div>
        </div>

        <!--Gráficos-->

        <div class="row">
            <div class="col">
                <partial name="_GastoTotalMes" />
            </div>
            <div class="col">
                <partial name="_GastoMes" />
            </div>            
        </div>

        <div class="row">
            <partial name="_GastosTotais" />
        </div>

        <div class="estatisticas">
            <div class="alert alert-primary">
                @await Component.InvokeAsync("Estatisticas");
            </div>
        </div>

        <div class="tabelaPrincipal">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>
                            Meses
                        </th>
                        <th>
                            Tipo de Despesa
                        </th>
                        <th>
                            Valor
                        </th>
                        <th>
                            Ação
                        </th>
                    </tr>
                </thead>
                <tbody>
            @foreach (var item in Model) {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Meses.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TipoDespesa.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Valor)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.DespesaId" class="btn btn-outline-info btn-sm">Atualizar</a> |                
                            <a onclick="ExibirModal(@item.DespesaId)" class="btn btn-outline-danger btn-sm">Excluir</a>
                        </td>
                    </tr>
            }
                </tbody>
            </table>
        </div>
    </div>
</div>

@Html.PagedListPager(Model, pagina => Url.Action("Index", "Despesas", new { pagina }), new PagedListRenderOptions
{
    LiElementClasses = new string[]{"page-itens"},
    PageClasses = new string[] {"page-link"},
})

<!--Tela Modal-->
<div class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Excluir</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Deseja prosseguir com a exclusão da despesa?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary btnExcluir">Sim</button>
                <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">Não</button>
            </div>
        </div>
    </div>
</div>

<!--Função Ajax para exibir modal-->
@section Scripts{

    <script src="~/bundle.min.js"></script>

    <script>

        /*Chamada de função para o gráfico*/
        CarregarDadosGastosMes();
        CarregarDadosGastosTotaisMes();
        CarregarDadosGastosTotais();

        function ExibirModal(id) {

            $(".modal").modal();

            $(".btnExcluir").on('click', function () {
                $.ajax({
                    url: "Despesas/Delete",
                    method: "POST",
                    data: { id: id },
                    success: function (data) {
                        $(".modal").modal('hide');
                        location.reload(true);
                    }
                });
            });
        }
    </script>
}